#!/bin/bash
echo "⚠️  WARNING: This will FORCE UPDATE the main branch with current branch"
echo ""
echo "Current branch: claude/debug-white-page-redirect-011CV2C1AuGcwGG8KZidfJiF"
echo "This will push all commits to main branch"
echo ""
echo "Run these commands:"
echo ""
echo "# Push current branch to main (force update)"
echo "git push origin claude/debug-white-page-redirect-011CV2C1AuGcwGG8KZidfJiF:main --force"
echo ""
echo "# Or checkout main and merge"
echo "git checkout main"
echo "git merge claude/debug-white-page-redirect-011CV2C1AuGcwGG8KZidfJiF --allow-unrelated-histories"
echo "git push origin main"
