// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://jhjpgdldjunkhdbtopbs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpoanBnZGxkanVua2hkYnRvcGJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5Mzk5OTMsImV4cCI6MjA3MTUxNTk5M30.TyNmKmM4rwgDIjngaIPkJKCKne781bcmzT6xF22kMg8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    flowType: 'pkce',
    autoRefreshToken: true,
    detectSessionInUrl: true,
    persistSession: true,
  },
});